In [1]:
import numpy as np

In [3]:
#create - from list
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1,2,3,4,5,"aiml"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'aiml'] <class 'numpy.ndarray'> <U21 (6,)


In [6]:
arr2D = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [13]:
#create
arr3 = np.zeros((2,3)) #prefill
print(arr3, arr3.shape)

arr4 = np.ones((3,3)) #prefill
print(arr4, arr4.shape)

arr5 = np.full((3,3), 100)#prefill with value
print(arr5, arr5.shape)

arr6 = np.eye((3)) #identitiy matrix
print(arr6, arr6.shape)

arr7 = np.arange(0,10,2) #range(start, end, step)
print(arr7, arr7.shape)

arr8 = np.linspace(1,100,4) #evenly spaced elements
print(arr8, arr8.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[0 2 4 6 8] (5,)
[  1.  34.  67. 100.] (4,)


In [15]:
#properties
array = np.array([1,2,34,5,5])

print(array.shape)
print(array.size)


(5,)
