In [1]:
import numpy as np

In [3]:
#create - from list
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1,2,3,4,5,"aiml"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'aiml'] <class 'numpy.ndarray'> <U21 (6,)


In [6]:
arr2D = np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2D, arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [9]:
#create
arr3 = np.zeros((2,3)) #prefill
print(arr3, arr3.shape)

arr4 = np.ones((3,3)) #prefill
print(arr4, arr4.shape)

arr5 = np.full((3,3), 100)#prefill with value
print(arr5, arr5.shape)

arr6 = np.eye((3,3)) #identitiy matrix
print(arr6, arr6.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)


TypeError: 'tuple' object cannot be interpreted as an integer